### ISSUE TITLE
Current todo

### ISSUE THREAD

**Issue by nmeylan** [nmeylan/rust-ro#25]
Skill todo:
- [ ] Implement skill physical attack
- [ ] apply skill damage to target

Status todo:
- [ ] Take job level into account
- [ ] Take armor stats into account
- [ ] Take weapon stats into account

Battle todo:
- [ ] Take refinement into account
- [ ] Take element into account
- [ ]  Implement magick attack
